create table if not exists public.signup_access_codes (
  id bigint generated by default as identity primary key,
  label text,
  code_hash text not null unique,
  is_active boolean not null default true,
  max_uses integer,
  used_count integer not null default 0,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  check (max_uses is null or max_uses >= 1),
  check (used_count >= 0)
);

alter table public.signup_access_codes enable row level security;

revoke all on table public.signup_access_codes from public;
revoke all on table public.signup_access_codes from anon;
revoke all on table public.signup_access_codes from authenticated;

create or replace function public.validate_signup_access_code(p_code text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  trimmed_code text := btrim(coalesce(p_code, ''));
  code_is_valid boolean;
begin
  if trimmed_code = '' then
    return false;
  end if;

  select exists (
    select 1
    from public.signup_access_codes sac
    where sac.is_active = true
      and sac.code_hash = md5(trimmed_code)
      and (sac.expires_at is null or sac.expires_at > now())
      and (sac.max_uses is null or sac.used_count < sac.max_uses)
  )
  into code_is_valid;

  return code_is_valid;
end;
$$;

revoke all on function public.validate_signup_access_code(text) from public;
grant execute on function public.validate_signup_access_code(text) to anon;
grant execute on function public.validate_signup_access_code(text) to authenticated;

insert into public.signup_access_codes (label, code_hash, is_active)
values ('Volunteer Signup 2026', md5('CKCVolunteer2026'), true)
on conflict (code_hash) do update
set is_active = excluded.is_active;
